// src/components/Rater.tsx
import { useRef } from "preact/hooks";
import { ratings } from "../base";
import styles from "./Rater.module.css";

function background(rating: number): string {
    if (rating % 1 === 0) return ratings[rating][1];
    return `linear-gradient(135deg, ${ratings[rating - 0.5][1]} 0%, ${ratings[rating + 0.5][1]} 100%)`;
}

export default function Rater({ text, rating, setRating }:
    { text: string, rating: number, setRating?: (r: number) => void }) {
    const updateRating = setRating && ((x: number) => {
        let newRating = rating + x;
        const max = ratings.length - 1;
        if (newRating === 0.5) newRating = x > 0 ? 1 : 0;
        else if (newRating > max) newRating = 0;
        else if (newRating < 0) newRating = max;
        setRating(newRating);
    });
    const handleClick = updateRating && ((e: MouseEvent) => {
        e.preventDefault();
        const step = e.shiftKey || e.altKey ? 0.5 : 1;
        updateRating(e.button ? -step : +step);
    });
    const handleKey = setRating && updateRating && ((e: KeyboardEvent) => {
        console.log("Key press: " + e.code);
        const x = Number(e.key);
        if (Number.isFinite(x)) {
            setRating(x && (x + 1) / 2);
        } else if (e.code === "Equal" || e.code === "Minus") {
            updateRating(e.code === "Equal" ? +0.5 : -0.5);
        }
    });
    const btn = setRating && useRef<HTMLButtonElement>(null);
    const focus = btn && (() => btn.current?.focus({ focusVisible: false, preventScroll: true }));
    const unfocus = btn && (() => btn.current?.blur());
    return (
        <div class={setRating ? styles.clickable : styles.noclick}
            onClick={handleClick} onContextMenu={handleClick}
            onKeyDown={handleKey} onMouseEnter={focus} onMouseLeave={unfocus}>
            <button style={{ background: background(rating) }} ref={btn} />
            <span>{text}</span>
        </div>
    );
}

// src/components/Rater.svelte
<script lang="ts">
    import { ratings } from "../base";

    const {
        text,
        rating,
        setRating,
        clickable,
    }: {
        text: string;
        rating: number;
        setRating?: (r: number) => void;
        clickable: boolean;
    } = $props();

    const handleClick = !setRating
        ? undefined
        : (e: MouseEvent) => {
              e.preventDefault();
              const step = e.shiftKey || e.altKey ? 0.5 : 1;
              let newRating = e.button ? rating - step : rating + step;
              const max = ratings.length - 1;
              if (newRating === 0.5) newRating = e.button ? 0 : 1;
              else if (newRating > max) newRating = 0;
              else if (newRating < 0) newRating = max;
              setRating(newRating);
          };

    function background(rating: number): string {
        if (rating % 1 === 0) return ratings[rating][1];
        return `linear-gradient(135deg, ${ratings[Math.floor(rating)][1]} 0%, ${ratings[Math.ceil(rating)][1]} 100%)`;
    }
</script>

<div
    class={clickable ? "clickable" : "noclick"}
    onclick={handleClick}
    oncontextmenu={handleClick}
>
    <button style={`background: ${background(rating)}`} />
    <span class="position">{text}</span>
</div>

<style>
    .clickable,
    .noclick {
        display: flex;
        flex-direction: row;
    }

    .clickable button,
    .noclick button {
        width: 1em;
        height: 1em;
        border: none;
        border-radius: 0;
        margin-right: 0.1875em;
        padding: 0 0.5em;
    }

    .clickable,
    .clickable * {
        cursor: pointer;
        user-select: none;
    }

    .position {
        margin-top: -0.05em;
    }

    /* Horrible hack */
    :global(body.screenshot) .noclick button,
    :global(body.screenshot) .clickable button {
        width: 16pt;
        height: 16pt;
    }
</style>
